USE [MusicInside]
DBCC CHECKIDENT ('Album', RESEED, 0);
GO
DBCC CHECKIDENT ('Artist', RESEED, 0);
GO
DBCC CHECKIDENT ('Featuring', RESEED, 0);
GO
DBCC CHECKIDENT ('File', RESEED, 0);
GO
DBCC CHECKIDENT ('Genre', RESEED, 0);
GO
DBCC CHECKIDENT ('Moment', RESEED, 0);
GO
DBCC CHECKIDENT ('Song', RESEED, 0);
GO
DBCC CHECKIDENT ('SongGenre', RESEED, 0);
GO
DBCC CHECKIDENT ('SongMoment', RESEED, 0);
GO
DBCC CHECKIDENT ('Statistic', RESEED, 0);
GO